spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false
    username: root
    password: 699685
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /imanager
graphql:
  servlet:
    corsEnabled: true
    enabled: true
    mapping: /imanager